Cu-2ar3am1: [Style] fyi asap remove force unwraps
vkrivozubov/dressed-app pull request #16
Opened 2022-04-09 16:06 UTC by Erokha

2022-04-09 16:06 UTC, vkrivozubov commented
Task linked: [CU-2ar3am1 [CLIENT] Убрать force unwrap в LookViewController](https://app.clickup.com/t/2ar3am1)

2022-04-09 16:09 UTC, Sashazakh approved these changes

2022-04-09 17:22 UTC, vkrivozubov approved these changes

2022-04-09 17:31 UTC, vkrivozubov requested changes
конфликт 
переделывать

2022-04-24 17:33 UTC, vkrivozubov approved these changes

2022-04-24 17:33 UTC, merged